#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the alternatingCharacters function below.
def alternatingCharacters(s):
    count=0
    for i in range(1,len(s)):
        if s[i]==s[i-1]:
            count +=1
    return count
