#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the arrayManipulation function below.
def arrayManipulation(n, queries):
    a=[0 for i in range(n)]
    for i in queries:
        a[i[0]-1] +=i[2]
        if i[1]<= n-1:
            a[i[1]] -= i[2]
    m=0
    x=0
    for i in a:
        x=x+i
        if x> m:
            m=x
    return m
