#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the candies function below.
def candies(n, arr):
    if len(arr)==1:
        return 1
    a = []
    if arr[0]<= arr[1]:
        a.append(1)
    else: a.append(0)
    for i in range(1,len(arr)-1):
        if arr[i]<= arr[i+1] and arr[i]<=arr[i-1]:
            a.append(1)
        else: a.append(0)
    if arr[len(arr)-1]<= arr[len(arr)-2]:
        a.append(1)
    else: a.append(0)
    n=2
    for i in range(1,len(arr)):
        if a[i]==1:        
            n = 2
            continue
        elif arr[i]>arr[i-1] :
            a[i]=n
            n = n + 1
        else: continue
    arr.reverse()
    a.reverse()
    n=2
    for i in range(1,len(arr)):
        if a[i]==1:        
            n = 2
            continue
        elif arr[i]>arr[i-1] and a[i]< n :     # have not been assigned value yet       
            a[i]=n
            n = n + 1
        else: continue
    return sum(a)
