#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the getMinimumCost function below.
def getMinimumCost(k, c):
    c.sort(reverse=True)
    s=0
    if k>=n:
        return sum(c)
    for i in range(int(n/k)+1):
        if i== int(n/k):
            s=s+(i+1)*sum(c[i*k:len(c)])
        else:
            s=s+(i+1)*sum(c[i*k:(i+1)*k])
    return s
