#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the maxSubsetSum function below.
def maxSubsetSum(arr):
    if len(arr)==1:
        return arr[0]
    if len(arr)==2:
        return max(arr)
    m1=arr[0]
    m2=max([arr[0],arr[1]])
    for i in range(2,len(arr)):
        m = m2 
        m2 = max([m2,arr[i],m1+arr[i]])
        m1 = m
    return m2
