#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumAbsoluteDifference function below.
def minimumAbsoluteDifference(arr):
    arr.sort()
    m=arr[1]-arr[0]
    for i in range(1,len(arr)):
        if arr[i]-arr[i-1]<m:
            m=arr[i]-arr[i-1]
    return m
