#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumBribes function below.
def minimumBribes(q):
    s=0
    for i in range(len(q)):
        d=q[i]- (i+1)
        if d>2:
            print("Too chaotic")
            return
        else:
            for j in range(max([0,q[i]-2]),i):
                if q[j]>q[i]:
                    s=s+1
    print(s)
    return 
