#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the substrCount function below.
def substrCount(n, s):
    count = 0
    i = 1
    for j in range(1,len(s)):
        if s[j] != s[j-1]:
            count += (i+1)*i/2
            i=1
        else:
            i += 1
    count += (i+1)*i/2 # the number of type 1
    for j in range(1,len(s)-1):
        if s[j-1] != s[j+1] or s[j] == s[j+1]:
            continue
        else :
            i=0
            for k in range(1,min([j,len(s)-1-j])+1):
                if s[j-k] == s[j+k] and s[j-k] == s[j-1] :
                    i += 1
                else:
                    break
            count += i
    return int(count)
